// Olivia Walker
//Using C++, display a matrix of numbers generated by rand function, its corresponding squares and square roots. Try adding the matrix bracket.

#include <iostream>

#include <cmath> // for sqrt function

#include <stdlib.h> // for rand number 

#include <ctime>

using namespace std;

int main() 
{

	int i = 0, j;

	int random;

	double randomNumbermatrix[10][10];

	//Random Numbers every time outputted
	srand(time(0));

	while (i < 5) {

		random = ((0 + rand()) % 10) + 1;

		for (j = 0; j <= i; j++) {

			if (!(random == randomNumbermatrix[i][0])) {

				randomNumbermatrix[i][0] = random;

				i++;

				break;

			}
		}
	}
	
	for (i = 0; i < 5; i++) {
		randomNumbermatrix[i][1] = (randomNumbermatrix[i][0]) * (randomNumbermatrix[i][0]);
		
		randomNumbermatrix[i][2] = sqrt(randomNumbermatrix[i][0]);

	}

	cout << " - - - -                                              - - - -\t\n";
	
	cout << "|                                                             \t|";

	cout << "\n\ Rand_Num          Squares       \tSquare_Roots          \t|\n";

	for (i = 0; i < 5; i++) {
		cout << "| ";

		for (j = 0; j < 3; j++) {

			cout << randomNumbermatrix[i][j] << "\t\t";

		}
		cout << "|\n";

	}

	cout << "|                                                          \t|\n";

	cout << "- - - - -                                             - - - -\n\n";
	return 0;
}


